export { TiltCard as LaTiltCard } from "../../components/MagicCard";
export { SpotlightCard as LaSpotlightCard } from "../../components/MagicCard";
export { GlassCard as LaGlassCard } from "../../components/MagicCard";
export { MagneticButton as LaMagneticButton } from "../../components/MagicCard";
export { ShimmerButton as LaShimmerButton } from "../../components/MagicCard";
export { AnimatedBorderCard as LaAnimatedBorderCard } from "../../components/MagicCard";
export { HolographicCard as LaHolographicCard } from "../../components/MagicCard";
export { NeonGlowCard as LaNeonGlowCard } from "../../components/MagicCard";
export { RippleButton as LaRippleButton } from "../../components/MagicCard";
export { GlowPulseButton as LaGlowPulseButton } from "../../components/MagicCard";
export { MorphButton as LaMorphButton } from "../../components/MagicCard";
export { morphVariants as laMorphVariants } from "../../components/MagicCard";
export { MagicCard as LaMagicCard } from "../../components/MagicCard";
export { HoverCard as LaHoverCard } from "../../components/MagicCard";
export { AnimatedCard as LaAnimatedCard } from "../../components/MagicCard";
export type { TiltCardProps as LaTiltCardProps } from "../../components/MagicCard";
export type { SpotlightCardProps as LaSpotlightCardProps } from "../../components/MagicCard";
export type { GlassCardProps as LaGlassCardProps } from "../../components/MagicCard";
export type { MagneticButtonProps as LaMagneticButtonProps } from "../../components/MagicCard";
export type { ShimmerButtonProps as LaShimmerButtonProps } from "../../components/MagicCard";
export type { AnimatedBorderCardProps as LaAnimatedBorderCardProps } from "../../components/MagicCard";
export type { HolographicCardProps as LaHolographicCardProps } from "../../components/MagicCard";
export type { NeonGlowCardProps as LaNeonGlowCardProps } from "../../components/MagicCard";
export type { RippleButtonProps as LaRippleButtonProps } from "../../components/MagicCard";
export type { GlowPulseButtonProps as LaGlowPulseButtonProps } from "../../components/MagicCard";
export type { MorphButtonProps as LaMorphButtonProps } from "../../components/MagicCard";
export type { MagicCardProps as LaMagicCardProps } from "../../components/MagicCard";
export type { HoverCardProps as LaHoverCardProps } from "../../components/MagicCard";
export type { AnimatedCardProps as LaAnimatedCardProps } from "../../components/MagicCard";
export type { MorphVariants as LaMorphVariants } from "../../components/MagicCard";
