export {
  TiltCard,
  SpotlightCard,
  GlassCard,
  MagneticButton,
  ShimmerButton,
  AnimatedBorderCard,
  HolographicCard,
  NeonGlowCard,
  RippleButton,
  GlowPulseButton,
  MorphButton,
  morphVariants,
} from "./MagicCard";
export type {
  TiltCardProps,
  SpotlightCardProps,
  GlassCardProps,
  MagneticButtonProps,
  ShimmerButtonProps,
  AnimatedBorderCardProps,
  HolographicCardProps,
  NeonGlowCardProps,
  RippleButtonProps,
  GlowPulseButtonProps,
  MorphButtonProps,
} from "./MagicCard";
